# -*- coding: utf-8 -*-
"""PRUEBA3.0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VWtRZrSElX3QvR80LIBhcPY8fmemRC26
"""

import pandas as pd
import random
import time
from IPython.display import clear_output

# ==============================================================================
# BLOQUE 1: LA FÁBRICA DE DATOS 🏗️
# ==============================================================================
print("⚙️  Sistema Online. Base de datos cargada y lista.")

datos_planes = [
    {"nombre": "Ahorro XS",     "gb": 3,   "precio": 10.00, "beneficio": "Solo WhatsApp Gratis"},
    {"nombre": "Básico S",      "gb": 5,   "precio": 15.00, "beneficio": "Redes Sociales (FB/Insta)"},
    {"nombre": "Conectado M",   "gb": 12,  "precio": 22.00, "beneficio": "Spotify Incluido"},
    {"nombre": "Social L",      "gb": 25,  "precio": 30.00, "beneficio": "Spotify + Instagram ilimitado"},
    {"nombre": "Streaming XL",  "gb": 40,  "precio": 40.00, "beneficio": "Suscripción Netflix SD"},
    {"nombre": "Pro XXL",       "gb": 60,  "precio": 55.00, "beneficio": "Netflix HD + Prime Video"},
    {"nombre": "Gamer Ultra",   "gb": 100, "precio": 70.00, "beneficio": "Baja latencia + Pase de Batalla"},
    {"nombre": "Empresarial",   "gb": 200, "precio": 90.00, "beneficio": "Roaming Mundial + IP Fija"}
]

df_planes = pd.DataFrame(datos_planes)
mapa_planes = df_planes.set_index('nombre').to_dict('index')

nombres = ["Juan", "María", "Carlos", "Ana", "Pedro", "Luisa", "Jorge", "Sofía", "Miguel", "Elena"]
apellidos = ["Pérez", "Gómez", "Ruiz", "Díaz", "Torres", "Vargas", "Mora", "Rios", "Castro", "Ortiz"]

casos_asignados = (['FANTASMA']*10 + ['PREVENTIVO']*10 + ['VIP']*10 + ['MEJORA']*10 + ['AHORRO']*10)
random.shuffle(casos_asignados)

lista_clientes = []
for i in range(1001, 1051):
    caso_actual = casos_asignados.pop()
    if caso_actual == 'FANTASMA':
        plan = random.choice(datos_planes[2:])
        consumo = random.uniform(0.1, 1.9)
    elif caso_actual == 'PREVENTIVO':
        plan = random.choice(datos_planes)
        consumo = plan['gb'] * random.uniform(0.85, 0.99)
    elif caso_actual == 'VIP':
        plan = random.choice(datos_planes[:5])
        consumo = random.uniform(55.0, 120.0)
    elif caso_actual == 'MEJORA':
        plan = random.choice(datos_planes)
        consumo = plan['gb'] * random.uniform(1.1, 1.5)
    elif caso_actual == 'AHORRO':
        plan = random.choice(datos_planes[2:])
        consumo = plan['gb'] * random.uniform(0.2, 0.45)

    lista_clientes.append({
        'id': i, 'nombre': f"{random.choice(nombres)} {random.choice(apellidos)}",
        'plan_actual': plan['nombre'], 'consumo_gb': round(consumo, 2), 'tipo_caso': caso_actual
    })
df_clientes = pd.DataFrame(lista_clientes)


# ==============================================================================
# BLOQUE 2: EL CEREBRO EMPÁTICO 🧠❤️
# ==============================================================================

def calcular_info_pago(id_cliente, precio_plan):
    dia_corte = (id_cliente % 28) + 1
    dia_limite = dia_corte + 5
    if dia_limite > 30: dia_limite -= 30
    total = precio_plan * 1.15
    return dia_corte, dia_limite, total

def obtener_script_variado(tipo, nombre, consumo, plan_nuevo, precio_nuevo, ahorro=0, beneficio=""):
    """Genera una respuesta aleatoria y humana."""

    if tipo == 'RETENCION':
        opciones = [
            f"Hola {nombre}. Estuve revisando tu consumo y noté que apenas usaste {consumo}GB. La verdad, no tiene sentido que pagues por algo que no usas. Te sugiero pasar al plan **{plan_nuevo}** para que pagues lo mínimo indispensable.",
            f"{nombre}, quiero ser honesto contigo: estás regalando dinero. Tu consumo de {consumo}GB es muy bajo para tu plan actual. Mi recomendación es ajustar tu tarifa al plan **{plan_nuevo}**.",
            f"Viendo tu historial, {nombre}, veo que realmente no necesitas tantos gigas ({consumo}GB usados). Si te cambias al **{plan_nuevo}**, mantienes tu línea pero pagas mucho menos."
        ]
        return random.choice(opciones)
    elif tipo == 'PREVENTIVO':
        opciones = [
            f"¡Ojo {nombre}! Me di cuenta de que estás al 90% de tus datos. Para evitar que te quedes desconectado en el peor momento, te recomiendo subir al **{plan_nuevo}**. Es solo una pequeña diferencia por tu tranquilidad.",
            f"Te comento, {nombre}, que estás muy cerca del límite de tu plan actual. Muchos clientes en tu situación prefieren asegurar su conexión con el plan **{plan_nuevo}**. ¿Qué opinas?",
            f"Estaba monitoreando tu cuenta y veo riesgo de corte. Llevas consumidos casi todos tus gigas. Para que navegues sin preocupaciones, la mejor opción es el **{plan_nuevo}**."
        ]
        return random.choice(opciones)
    elif tipo == 'VIP':
        opciones = [
            f"¡Wow, {nombre}! Tu consumo de {consumo}GB es impresionante. Se nota que le sacas el jugo al internet. Para alguien con tu perfil, el único plan que da la talla es el **{plan_nuevo}**.",
            f"Analizando tu perfil, veo que eres un usuario exigente. Tu plan actual se te queda corto. Para disfrutar de verdad (y con baja latencia), te sugiero el **{plan_nuevo}**.",
            f"{nombre}, francamente tu consumo es de otro nivel. Mereces un servicio Premium. El plan **{plan_nuevo}** está diseñado exactamente para usuarios Power como tú."
        ]
        return random.choice(opciones)
    elif tipo == 'MEJORA':
        opciones = [
            f"Hola {nombre}. Veo que tus datos se agotaron ({consumo}GB consumidos). Sé que es molesto navegar lento, por eso te tengo una solución rápida: el plan **{plan_nuevo}**.",
            f"{nombre}, noté que te pasaste de tu límite. Para que no sufras con la velocidad reducida, lo más inteligente sería actualizarte al **{plan_nuevo}** ahora mismo.",
            f"Parece que este mes necesitaste más internet de lo normal. Para cubrir ese exceso y que estés tranquilo, mi consejo es activar el plan **{plan_nuevo}**."
        ]
        return random.choice(opciones)
    elif tipo == 'AHORRO':
        opciones = [
            f"{nombre}, traigo buenas noticias. Analicé tu factura y veo que puedes pagar menos. Como solo usas {consumo}GB, te quedaría perfecto el plan **{plan_nuevo}**. ¡Te ahorrarías ${ahorro:.2f}!",
            f"Siendo sincero, {nombre}, tu plan actual es demasiado grande para lo que consumes hoy ({consumo}GB). ¿Por qué no te pasas al **{plan_nuevo}** y usas ese dinero extra para otra cosa?",
            f"Te propongo algo para cuidar tu bolsillo: He visto que te sobran muchos gigas. Con el plan **{plan_nuevo}** tendrías suficiente y pagarías menos cada mes."
        ]
        return random.choice(opciones)
    else:
        opciones = [
            f"Juan, estuve revisando tu consumo y la verdad es que estás usando tu plan de forma ideal 👍. No necesitas cambios.",
            f"Todo en orden, {nombre}. Tu plan actual se ajusta como un guante a tu consumo de {consumo}GB. ¡Sigue así!",
            f"He revisado tu cuenta y honestamente, tienes el mejor plan posible para ti. No te recomendaría cambiar nada por ahora."
        ]
        return random.choice(opciones)

def analizar_perfil(id_cliente):
    row = df_clientes[df_clientes['id'] == id_cliente]
    if row.empty: return None

    idx = row.index[0]; cliente = row.iloc[0]
    nombre = cliente['nombre'].split()[0]
    plan_actual = cliente['plan_actual']; consumo = cliente['consumo_gb']
    datos_actual = mapa_planes[plan_actual]
    limite_actual = datos_actual['gb']; precio_actual = datos_actual['precio']

    perfil = {
        'indice': idx, 'nombre': nombre, 'plan_actual': plan_actual,
        'consumo': consumo, 'limite': limite_actual, 'precio_actual': precio_actual,
        'recomendacion': None
    }

    tipo_caso = 'OK'
    mejor = None

    if consumo < 2.0 and plan_actual != "Ahorro XS":
        tipo_caso = 'RETENCION'
        mejor = df_planes[df_planes['nombre'] == "Ahorro XS"].iloc[0]
    elif (consumo >= limite_actual * 0.85) and (consumo <= limite_actual):
        tipo_caso = 'PREVENTIVO'
        opciones = df_planes[df_planes['gb'] > limite_actual]
        mejor = opciones.sort_values('precio').iloc[0]
    elif consumo > 50.0 and plan_actual not in ["Gamer Ultra", "Empresarial"]:
        tipo_caso = 'VIP'
        mejor = df_planes[df_planes['nombre'] == "Gamer Ultra"].iloc[0]
    elif consumo > limite_actual:
        tipo_caso = 'MEJORA'
        opciones = df_planes[df_planes['gb'] > consumo]
        mejor = opciones.sort_values('precio').iloc[0]
    elif consumo < (limite_actual * 0.5):
        tipo_caso = 'AHORRO'
        opciones = df_planes[(df_planes['gb'] >= consumo * 1.2) & (df_planes['precio'] < precio_actual)]
        mejor = opciones.sort_values('precio').iloc[0]
    else:
        tipo_caso = 'OK'
        mejor = None

    if mejor is not None:
        script = obtener_script_variado(
            tipo_caso, nombre, consumo, mejor['nombre'], mejor['precio'],
            ahorro=(precio_actual - mejor['precio']), beneficio=mejor['beneficio']
        )
        perfil['recomendacion'] = {'tipo': tipo_caso, 'plan_nuevo': mejor['nombre'], 'script': script}
    else:
        script = obtener_script_variado('OK', nombre, consumo, None, None)
        perfil['recomendacion'] = {'tipo': 'OK', 'plan_nuevo': None, 'script': script}

    return perfil

def comparar_planes_texto(plan_actual, nombre_nuevo):
    actual = mapa_planes[plan_actual]
    nuevo = mapa_planes[nombre_nuevo]
    return f"\n📊 COMPARATIVA RÁPIDA\n   🔹 TU PLAN: {plan_actual} (${actual['precio']}) | {actual['gb']}GB\n   🔸 NUEVO:   {nombre_nuevo} (${nuevo['precio']}) | {nuevo['gb']}GB\n   🎁 Extra:   {nuevo['beneficio']}"

# ==============================================================================
# BLOQUE 3: EL CHAT INTEGRAL DETALLADO 💬
# ==============================================================================

def imprimir_titulo_centrado(texto, ancho=60):
    print("\n" + "═"*ancho)
    print(texto.center(ancho))
    print("═"*ancho)

def chat_sistema_integral():
    imprimir_titulo_centrado("CENTRO DE EXPERIENCIA AL CLIENTE (IA)")

    while True:
        # --- LOGIN ---
        entrada = input("\n🔐 AGENTE: Por favor, ingresa tu ID de Cliente (1001-1050): ")
        if entrada.lower() in ['salir', 'exit']:
            print("👋 ¡Que tengas un excelente día!"); break
        if not entrada.isdigit(): continue

        id_cliente = int(entrada)
        datos = analizar_perfil(id_cliente)
        if not datos:
            print("❌ Mmm, no encuentro ese ID. Intenta de nuevo."); continue

        print(f"\n👋 Hola {datos['nombre']}. Qué gusto saludarte.")
        time.sleep(0.5)

        # FASE 1: DIAGNÓSTICO
        rec = datos['recomendacion']
        print(f"\n🤖 AGENTE: {rec['script']}")

        plan_actual_sesion = datos['plan_actual']

        if rec['plan_nuevo']:
            print("\n   1. ✅ Aceptar sugerencia")
            print("   2. 🔍 Ver otras opciones")
            print("   3. ❌ Ignorar por ahora")

            opcion = input("\n👤 TÚ (1, 2, 3): ")

            if opcion == '1':
                df_clientes.at[datos['indice'], 'plan_actual'] = rec['plan_nuevo']
                plan_actual_sesion = rec['plan_nuevo']
                print(f"🎉 ¡Excelente decisión! El plan [{rec['plan_nuevo']}] ya está activo.")

                print("\n🤖 AGENTE: Por cierto, ¿quieres que revisemos las fechas de pago del nuevo plan?")
                if 'si' in input("👤 TÚ (si/no): ").lower():
                    corte, limite, total = calcular_info_pago(id_cliente, mapa_planes[plan_actual_sesion]['precio'])
                    print(f"\n📝 NUEVO CONTRATO: Corte: Día {corte} | Pagar hasta: Día {limite} | Total: ${total:.2f}")

            elif opcion == '2':
                print("\n🤖 AGENTE: Claro que sí. Déjame mostrarte el catálogo completo en el menú.")

        # FASE 2: MENÚ METÓDICO
        while True:
            # Encabezado del menú centrado y limpio
            ancho_menu = 50
            print("\n" + "─"*ancho_menu)
            print(f"MENÚ PRINCIPAL DE {datos['nombre'].upper()}".center(ancho_menu))
            print(f"(Plan Actual: {plan_actual_sesion})".center(ancho_menu))
            print("─"*ancho_menu)
            print("   1. 📊 Consultar saldo y consumo actual")
            print("   2. 💳 Ver fechas de pago y factura")
            print("   3. 📱 Ver catálogo / CAMBIAR PLAN")
            print("   4. ⭐ Calificar atención")
            print("   5. 👋 Finalizar Sesión")

            menu_op = input("\n👤 Elige una opción: ")

            if menu_op == '1':
                print("🤖 AGENTE: Dame un segundo para verificar tus datos...")
                time.sleep(0.5)
                consumo = datos['consumo']
                limite = mapa_planes[plan_actual_sesion]['gb']
                porcentaje = min(100, (consumo / limite) * 100)
                restante = max(0, limite - consumo)
                barras = int(porcentaje / 10)
                visual_bar = "█" * barras + "░" * (10 - barras)

                print(f"\n📊 REPORTE DE CONSUMO DETALLADO")
                print(f"   ───────────────────────────────────")
                print(f"   Plan Contratado: {plan_actual_sesion} ({limite} GB)")
                print(f"   Uso Visual:      [{visual_bar}] {porcentaje:.1f}%")
                print(f"   ───────────────────────────────────")
                print(f"   ⬇️  Consumido:    {consumo:.2f} GB")
                print(f"   ✅  Disponible:   {restante:.2f} GB")
                print(f"   🔄  Renovación:   Día {(id_cliente % 28) + 1} del próximo mes")
                print(f"   ───────────────────────────────────")
                if consumo > limite: print("   ⚠️  ESTADO: Navegación reducida (Excedido)")
                else: print("   🚀  ESTADO: Alta Velocidad Activa")
                input("   (Presiona Enter para volver)")

            elif menu_op == '2':
                print("🤖 AGENTE: Claro, aquí tienes el detalle de tu factura...")
                time.sleep(0.5)
                corte, limite, total = calcular_info_pago(id_cliente, mapa_planes[plan_actual_sesion]['precio'])
                subtotal = mapa_planes[plan_actual_sesion]['precio']
                iva = subtotal * 0.15

                print(f"\n💳 DETALLE DE FACTURACIÓN")
                print(f"   Factura Nro:     F-{random.randint(10000, 99999)}")
                print(f"   Periodo:         Actual")
                print(f"   ───────────────────────────────────")
                print(f"   Subtotal Plan:   ${subtotal:.2f}")
                print(f"   IVA (15%):       ${iva:.2f}")
                print(f"   ───────────────────────────────────")
                print(f"   💰 TOTAL A PAGAR: ${total:.2f}")
                print(f"   ───────────────────────────────────")
                print(f"   📅 Fecha Corte:   Día {corte}")
                print(f"   ⚠️ Vence el:      Día {limite}")
                print(f"   🏦 Estado:        Pendiente de Pago")
                input("   (Presiona Enter para volver)")

            elif menu_op == '3':
                print("\n📱 CATÁLOGO DE SERVICIOS")
                print(f"   {'PLAN':<13} | {'GB':<3} | {'PRECIO':<6} | {'BENEFICIO PRINCIPAL'}")
                print("   " + "─"*60)

                for p in datos_planes:
                    marca = "✅ (ACTUAL)" if p['nombre'] == plan_actual_sesion else ""
                    print(f"   {p['nombre']:<13} | {p['gb']:<3} | ${p['precio']:<6} | {p['beneficio']} {marca}")

                print("\n🤖 AGENTE: ¿Hay alguno que te llame la atención? Escribe el nombre (o Enter para volver).")
                seleccion = input("👤 TÚ: ")

                plan_obj = next((p for p in datos_planes if p['nombre'].lower() == seleccion.lower()), None)

                if plan_obj:
                    if plan_obj['nombre'] == plan_actual_sesion:
                        print("🤖 AGENTE: ¡Ese ya es tu plan actual! Estás cubierto.")
                    else:
                        print(comparar_planes_texto(plan_actual_sesion, plan_obj['nombre']))
                        confirma = input(f"🤖 AGENTE: La decisión es tuya. ¿Te gustaría probar el plan [{plan_obj['nombre']}]? (si/no): ")

                        if 'si' in confirma.lower():
                            # EL CLIENTE DIJO SÍ
                            df_clientes.at[datos['indice'], 'plan_actual'] = plan_obj['nombre']
                            plan_actual_sesion = plan_obj['nombre']
                            print(f"✅ ¡Hecho! Bienvenido a tu nuevo plan {plan_obj['nombre']}.")
                            corte, limite, total = calcular_info_pago(id_cliente, plan_obj['precio'])
                            print(f"ℹ️  Nota: Verás el ajuste en tu factura del día {corte}.")
                        else:
                            # EL CLIENTE DIJO NO -> AQUÍ ENTRA LA NUEVA LÓGICA DE OBJECIONES
                            print(f"\n🤖 AGENTE: Entiendo. No queremos que te cambies si no estás 100% seguro.")
                            motivo = input("   ¿Qué fue lo que no te convenció? (precio / gigas / otro): ")

                            nuevo_sugerido = None

                            # Lógica para encontrar alternativa
                            if "precio" in motivo.lower() or "caro" in motivo.lower():
                                print("🤖 AGENTE: Comprendo, buscas cuidar el bolsillo.")
                                posibles = df_planes[df_planes['precio'] < plan_obj['precio']]
                                if not posibles.empty:
                                    nuevo_sugerido = posibles.iloc[-1] # El mejor de los baratos

                            elif "gigas" in motivo.lower() or "poco" in motivo.lower():
                                 print("🤖 AGENTE: Entendido, necesitas más potencia.")
                                 posibles = df_planes[df_planes['gb'] > plan_obj['gb']]
                                 if not posibles.empty:
                                    nuevo_sugerido = posibles.iloc[0] # El siguiente superior

                            if nuevo_sugerido is not None:
                                 print(f"   Mira, pensando en lo que me dices, el plan [{nuevo_sugerido['nombre']}] podría ser el ideal.")
                                 print(f"   Cuesta ${nuevo_sugerido['precio']} y tiene {nuevo_sugerido['gb']}GB.")
                                 intento_2 = input(f"   ¿Le damos una oportunidad a este? (si/no): ")
                                 if 'si' in intento_2.lower():
                                     df_clientes.at[datos['indice'], 'plan_actual'] = nuevo_sugerido['nombre']
                                     plan_actual_sesion = nuevo_sugerido['nombre']
                                     print(f"🎉 ¡Resuelto! Activamos el plan [{nuevo_sugerido['nombre']}].")
                                 else:
                                     print("🤖 AGENTE: Vale, no te preocupes. Tu plan actual sigue activo.")
                            else:
                                 print("🤖 AGENTE: Entendido. A veces es mejor mantener lo que uno ya conoce.")

                elif seleccion != "":
                    print("❌ Mmm, no encuentro un plan con ese nombre. Revisa la lista.")

            elif menu_op == '4':
                print("🤖 AGENTE: Nos ayuda mucho saber cómo lo hicimos.")
                input("\n⭐ Del 1 al 5, ¿qué nota me pones hoy?: ")
                print("🤖 AGENTE: ¡Muchas gracias por tu tiempo!")

            elif menu_op == '5':
                print(f"\n🤖 AGENTE: Fue un placer atenderte, {datos['nombre']}. ¡Cuídate mucho!")
                time.sleep(1)
                break

            else:
                print("❌ Esa opción no la reconozco. Intenta con 1, 2, 3, 4 o 5.")

# ¡DALE PLAY! 🚀
chat_sistema_integral()

